### ISSUE TITLE
Alaric Ticket

### ISSUE THREAD

**Issue by R2D2VaderBeef** [HoneycombRacing/honeycombracing.github.io#5]
Alaric wants these changes made:
- [x] On the sponsor page make the logos appear on the left and the bios on the right.
- [x] On the socials page centre the Instagram thing or make it wider
- [x] On the socials page make the first 2 tiktoks be next to each other
- [x] On the socials page centre the YT video
- [x] On the projects page change the Green bio to say "project" rather than "sub-brand"

I'll also try and get the missing sponsor images fixed on the sponsors page (if they are fixable using the massive resolution source files).

**Comment by R2D2VaderBeef** [comment]
Additional changes:

- Swapped out the Instagram embed for Instagram's native embed so it doesn't stop working after 200 page views
- Fix #3 by removing all the srcsets
- Added the social icons to the top of the social page
- Various minor style changes (mostly adding / removing whitespace and adding padding for lower widths)
- Moved the body section of each sub-page up the page to a better-looking place

**Comment by kamicavi** [comment]
Thank you so much!!
